/*
  Warnings:

  - The values [WALK_CREATION,WALK_UPDATE,WALK_DELETE] on the enum `TokenTransactionType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "TokenTransactionType_new" AS ENUM ('SIGNUP_BONUS', 'PURCHASE', 'USAGE', 'REFUND', 'BONUS', 'ADMIN_ADJUSTMENT', 'PET_CREATION', 'PET_CREATION_LEGACY', 'PET_UPDATE', 'PET_UPDATE_LEGACY', 'PET_DELETE', 'PET_DELETE_LEGACY', 'VITAL_SIGNS_CREATION', 'VITAL_SIGNS_CREATION_LEGACY', 'VITAL_SIGNS_UPDATE', 'VITAL_SIGNS_UPDATE_LEGACY', 'VITAL_SIGNS_DELETE', 'VITAL_SIGNS_DELETE_LEGACY', 'PAIN_SCORE_CREATION', 'PAIN_SCORE_CREATION_LEGACY', 'PAIN_SCORE_UPDATE', 'PAIN_SCORE_UPDATE_LEGACY', 'PAIN_SCORE_DELETE', 'PAIN_SCORE_DELETE_LEGACY', 'FEEDING_CREATION', 'FEEDING_CREATION_LEGACY', 'FEEDING_UPDATE', 'FEEDING_UPDATE_LEGACY', 'FEEDING_DELETE', 'FEEDING_DELETE_LEGACY', 'APPOINTMENT_CREATION', 'APPOINTMENT_CREATION_LEGACY', 'APPOINTMENT_UPDATE', 'APPOINTMENT_UPDATE_LEGACY', 'APPOINTMENT_DELETE', 'APPOINTMENT_DELETE_LEGACY', 'WATER_CREATION', 'WATER_CREATION_LEGACY', 'WATER_UPDATE', 'WATER_UPDATE_LEGACY', 'WATER_DELETE', 'WATER_DELETE_LEGACY', 'MEDICATION_CREATION', 'MEDICATION_CREATION_LEGACY', 'MEDICATION_UPDATE', 'MEDICATION_UPDATE_LEGACY', 'MEDICATION_DELETE', 'MEDICATION_DELETE_LEGACY', 'BLOOD_SUGAR_CREATION', 'BLOOD_SUGAR_CREATION_LEGACY', 'BLOOD_SUGAR_UPDATE', 'BLOOD_SUGAR_UPDATE_LEGACY', 'BLOOD_SUGAR_DELETE', 'BLOOD_SUGAR_DELETE_LEGACY', 'SEIZURE_TRACKING_CREATION', 'SEIZURE_TRACKING_CREATION_LEGACY', 'SEIZURE_TRACKING_UPDATE', 'SEIZURE_TRACKING_UPDATE_LEGACY', 'SEIZURE_TRACKING_DELETE', 'SEIZURE_TRACKING_DELETE_LEGACY', 'MOVEMENT_CREATION', 'MOVEMENT_CREATION_LEGACY', 'MOVEMENT_UPDATE', 'MOVEMENT_UPDATE_LEGACY', 'MOVEMENT_DELETE', 'MOVEMENT_DELETE_LEGACY', 'GALLERY_ITEM_CREATION', 'GALLERY_ITEM_CREATION_LEGACY', 'GALLERY_ITEM_DELETE', 'GALLERY_ITEM_DELETE_LEGACY', 'GALLERY_ITEM_UPDATE', 'GALLERY_ITEM_UPDATE_LEGACY');
ALTER TABLE "TokenTransaction" ALTER COLUMN "type" TYPE "TokenTransactionType_new" USING ("type"::text::"TokenTransactionType_new");
ALTER TYPE "TokenTransactionType" RENAME TO "TokenTransactionType_old";
ALTER TYPE "TokenTransactionType_new" RENAME TO "TokenTransactionType";
DROP TYPE "TokenTransactionType_old";
COMMIT;
